# Generated by Django 5.1.3 on 2024-12-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_commande_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='adresse',
            new_name='localisation',
        ),
    ]
