# Generated by Django 5.1.3 on 2024-12-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_adresse_commande_localisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='user',
            new_name='user_id',
        ),
    ]
