# Generated by Django 5.1.3 on 2024-12-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='tel',
            field=models.BigIntegerField(default=654158175),
            preserve_default=False,
        ),
    ]
