# Generated by Django 5.1.3 on 2024-12-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_commande_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='localisation',
            new_name='adresseDeLivraison',
        ),
        migrations.AddField(
            model_name='commande',
            name='paiement',
            field=models.CharField(default='Dschang', max_length=300),
            preserve_default=False,
        ),
    ]
