# Generated by Django 5.1.3 on 2024-12-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_commande_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='paiement',
        ),
    ]
