# Generated by Django 5.1.3 on 2024-12-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_payment_card_number_remove_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='payment',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
