# Generated by Django 5.1.3 on 2024-12-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification_du_systeme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(default=654158175, max_length=9),
            preserve_default=False,
        ),
    ]
