# Generated by Django 5.1.3 on 2024-12-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification_du_systeme', '0002_customuser_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='last_name',
            new_name='prenom',
        ),
    ]
