# Generated by Django 5.1.3 on 2024-12-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification_du_systeme', '0003_rename_first_name_customuser_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
    ]
